######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 08:26:43 2010
######################################################################

QT       += core gui widgets svg
TEMPLATE = app
TARGET = Sudoku
DEPENDPATH += .
INCLUDEPATH += .

win32: RC_ICONS = sudoku.ico

# Input
HEADERS += mainwindow.h sudokuwidget.h
SOURCES += main.cpp mainwindow.cpp sudokuwidget.cpp

LIBS += -L./ \
    -lqwt
